# Generated by Django 3.2.8 on 2021-10-15 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emkk_site', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='result',
            field=models.CharField(choices=[('route_completed', 'Route Completed'), ('on_route', 'On Route'), ('take_papers', 'Take Papers'), ('on_review', 'On Review'), ('at_issuer', 'At Issuer'), ('on_rework', 'On Rework'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='on_review', max_length=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('route_completed', 'Route Completed'), ('on_route', 'On Route'), ('take_papers', 'Take Papers'), ('on_review', 'On Review'), ('at_issuer', 'At Issuer'), ('on_rework', 'On Rework'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='on_review', max_length=30),
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pedestrian', 'Pedestrian'), ('cycling', 'Cycling'), ('mountain', 'Mountain'), ('water', 'Water'), ('ski', 'Ski')], max_length=30)),
                ('difficulty_category', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripsOnReviewByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emkk_site.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
