# Generated by Django 3.2.8 on 2021-10-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('pedestrian', 'Pedestrian'), ('cycling', 'Cycling'), ('mountain', 'Mountain'), ('water', 'Water'), ('ski', 'Ski')], max_length=30)),
                ('difficulty_category', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emkk_site.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='emkk_site.UserRole'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('route_completed', 'Route Completed'), ('on_route', 'On Route'), ('created', 'Created'), ('on_review', 'On Review'), ('at_issuer', 'At Issuer'), ('in_rework', 'On Rework'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='created', max_length=30)),
                ('kind', models.CharField(blank=True, choices=[('pedestrian', 'Pedestrian'), ('cycling', 'Cycling'), ('mountain', 'Mountain'), ('water', 'Water'), ('ski', 'Ski')], max_length=30)),
                ('group_name', models.CharField(max_length=100)),
                ('difficulty_category', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('participants_count', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coordinator_info', models.TextField()),
                ('insurance_info', models.TextField()),
                ('start_apply', models.TextField(null=True)),
                ('end_apply', models.TextField(null=True)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emkk_site.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('route_completed', 'Route Completed'), ('on_route', 'On Route'), ('created', 'Created'), ('on_review', 'On Review'), ('at_issuer', 'At Issuer'), ('in_rework', 'On Rework'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='on_review', max_length=30)),
                ('result_comment', models.TextField()),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emkk_site.user')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emkk_site.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('content', models.BinaryField()),
                ('content_type', models.CharField(max_length=50, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emkk_site.trip')),
            ],
        ),
    ]
